# Generated by Django 3.2.19 on 2023-06-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='step_description',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='step_image',
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_description', models.TextField()),
                ('step_image', models.ImageField(blank=True, upload_to='images/')),
                ('order', models.PositiveIntegerField()),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.tutorial')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
