# Generated by Django 3.2.19 on 2023-06-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_alter_step_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
